aiPlatforms:
  Watsonx:
    platform: watsonx
    credentials:
      api_key: $WATSONX_APIKEY
      api_base: https://us-south.ml.cloud.ibm.com
      api_project_id: $WATSONX_PID
models:
  granite-code-inst20:
    id: ibm/granite-20b-code-instruct
    host: Watsonx
    parameters:
      decoding_method: greedy
      max_new_tokens: 1024
      random_seed: 10
      temperature: 0
generation:
  models:
    - granite-code-inst20
  maxIter: 3
  features:
    rag: false
    staticChecks: true
    llmEval: false

