aiPlatforms:
  Watsonx:
    platform: watsonx
    credentials:
      api_key: $WATSONX_APIKEY
      api_base: https://us-south.ml.cloud.ibm.com
      api_project_id: 02c995f9-d57b-444e-8833-0ab8e404f139
models:
  encoder-slate:
    id: ibm/slate-125m-english-rtrvr-v2
    host: Watsonx
    parameters:
      truncate_input_tokens: 500
  granite-code-inst20:
    id: ibm/granite-20b-code-instruct
    host: Watsonx
    parameters:
      decoding_method: greedy
      max_new_tokens: 1024
      random_seed: 10
      temperature: 0
  encoder-slate-documents-query:
      id: ibm/slate-125m-english-rtrvr-v2
      host: Watsonx
      parameters:
        truncate_input_tokens: 500
        return_options:
          documents: true
          query: true
generation:
  models:
    - granite-code-inst20
  maxIter: 3
  features:
    rag: false
    staticChecks: true
    llmEval:
       enabled: false
  retrieval:
    models:
      - encoder-slate
    topK: 10
    rerank:
      model: encoder-slate-documents-query
      topN : 4

