aiPlatforms:
  BAM:
    platform: bam
    apiKey: $BAM_KEY
    apiBase: https://bam-api.res.ibm.com/
models:
  encoder-slate:
    id: ibm/slate.30m.english.rtrvr
    host: BAM
    parameters:
      truncate_input_tokens: true
  granite-api:
    id: ibm/granite-20b-code-instruct-unified-api
    host: BAM
    parameters:
      decoding_method: greedy
      max_new_tokens: 1024
      random_seed: 10
      temperature: 0
  bge-large-en-v1:
      id: baai/bge-large-en-v1.5
      host: BAM
      parameters:
        truncate_input_tokens: true
        return_options:
          documents: true
          query: true
  granite-multilang :      
    id: ibm/granite-20b-multilang-lab-rc
    host: BAM
    parameters:
      decoding_method: greedy
      max_new_tokens: 4096
      random_seed: 10
      temperature: 0
  llama3 :      
    id: peri/llama-3-70b-instruct
    host: BAM
    parameters:
      decoding_method: greedy
      max_new_tokens: 2048
      temperature: 0
retrieval:
  # (required) Models to use for retrieval, ordered by preference
  models:
    - encoder-slate
  topK: 10
  rerank:
      # (optional) Maximum number of results to return
      topN: 4
      model: bge-large-en-v1
generation:
  models:
    - granite-api
  maxIter: 3
evaluation:
  models:
   - llama3
apiKey: $INSTANA_KEY
auth: apiToken