aiPlatforms:
  BAM:
    platform: bam
    apiKey: $BAM_KEY
    apiBase: https://bam-api.res.ibm.com/
models:
  encoder-slate:
    id: ibm/slate.30m.english.rtrvr
    host: BAM
    parameters:
      truncate_input_tokens: true
  granite-api20:
    id: ibm/granite-20b-code-instruct-unified-api
    host: BAM
    parameters:
      decoding_method: greedy
      max_new_tokens: 1024
      random_seed: 10
      temperature: 0
  granite-api8:
    id: ibm/granite-8b-unified-api-model-v2
    host: BAM
    parameters:
      decoding_method: greedy
      max_new_tokens: 1024
      random_seed: 10
      temperature: 0
  bge-large-en-v1:
      id: baai/bge-large-en-v1.5
      host: BAM
      parameters:
        truncate_input_tokens: true
        return_options:
          documents: true
          query: true
retrieval:
  persistentVectorStoreDir: ./var/vs
  models:
    - encoder-slate
  topK: 10
  rerank:
    model: bge-large-en-v1
    # (optional) Maximum number of results to return
    topN : 4

generation:
  models:
    - granite-api20
  maxIter: 5
evaluation:
  models:
   - llama3
apiKey: $INSTANA_KEY
auth: apiToken